# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/kaijin/TWCKaijin/Auto-meta-heuristic-with-transformers

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/kaijin/TWCKaijin/Auto-meta-heuristic-with-transformers

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kaijin/TWCKaijin/Auto-meta-heuristic-with-transformers/CMakeFiles /Users/kaijin/TWCKaijin/Auto-meta-heuristic-with-transformers//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kaijin/TWCKaijin/Auto-meta-heuristic-with-transformers/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DE_cpp

# Build rule for target.
DE_cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DE_cpp
.PHONY : DE_cpp

# fast build rule for target.
DE_cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DE_cpp.dir/build.make CMakeFiles/DE_cpp.dir/build
.PHONY : DE_cpp/fast

#=============================================================================
# Target rules for targets named hyper_cpp

# Build rule for target.
hyper_cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hyper_cpp
.PHONY : hyper_cpp

# fast build rule for target.
hyper_cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper_cpp.dir/build.make CMakeFiles/hyper_cpp.dir/build
.PHONY : hyper_cpp/fast

src/cpp/DE.o: src/cpp/DE.cpp.o
.PHONY : src/cpp/DE.o

# target to build an object file
src/cpp/DE.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DE_cpp.dir/build.make CMakeFiles/DE_cpp.dir/src/cpp/DE.cpp.o
.PHONY : src/cpp/DE.cpp.o

src/cpp/DE.i: src/cpp/DE.cpp.i
.PHONY : src/cpp/DE.i

# target to preprocess a source file
src/cpp/DE.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DE_cpp.dir/build.make CMakeFiles/DE_cpp.dir/src/cpp/DE.cpp.i
.PHONY : src/cpp/DE.cpp.i

src/cpp/DE.s: src/cpp/DE.cpp.s
.PHONY : src/cpp/DE.s

# target to generate assembly for a file
src/cpp/DE.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DE_cpp.dir/build.make CMakeFiles/DE_cpp.dir/src/cpp/DE.cpp.s
.PHONY : src/cpp/DE.cpp.s

src/cpp/hyper.o: src/cpp/hyper.cpp.o
.PHONY : src/cpp/hyper.o

# target to build an object file
src/cpp/hyper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper_cpp.dir/build.make CMakeFiles/hyper_cpp.dir/src/cpp/hyper.cpp.o
.PHONY : src/cpp/hyper.cpp.o

src/cpp/hyper.i: src/cpp/hyper.cpp.i
.PHONY : src/cpp/hyper.i

# target to preprocess a source file
src/cpp/hyper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper_cpp.dir/build.make CMakeFiles/hyper_cpp.dir/src/cpp/hyper.cpp.i
.PHONY : src/cpp/hyper.cpp.i

src/cpp/hyper.s: src/cpp/hyper.cpp.s
.PHONY : src/cpp/hyper.s

# target to generate assembly for a file
src/cpp/hyper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper_cpp.dir/build.make CMakeFiles/hyper_cpp.dir/src/cpp/hyper.cpp.s
.PHONY : src/cpp/hyper.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... DE_cpp"
	@echo "... hyper_cpp"
	@echo "... src/cpp/DE.o"
	@echo "... src/cpp/DE.i"
	@echo "... src/cpp/DE.s"
	@echo "... src/cpp/hyper.o"
	@echo "... src/cpp/hyper.i"
	@echo "... src/cpp/hyper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

